FORMAT: 1A

# Courses

Courses is a simple api allowing users to see the list of available courses, add own courses.

## List of courses[/courses]

### List All Courses [GET]

+ Response 200 (application/json)
        [
               {
                    "name": "English with Mr. Peterson I",
                    "description": "This course covers beginner level of English Grammar and Vocabulary and something else",
                    "category": 1,
                    "logo": null,
                    "contacts": 1,
                    "branches": 1
                },
                {
                    "name": "Intro to Programming with Python",
                    "description": "In this course we will discover wonderful world of programming.\r\nDr. Chuck will be your guide through your journey.",
                    "category": 2,
                    "logo": null,
                    "contacts": 2,
                    "branches": 2
                }
        ]

